functionDir: "~/r_code/functions"
categoryTag: "pw"
# baseDir: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/10 - TNT/03.05.2023 Revision/"
baseDir: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/08 - Personal Wash/March 2023 Transition"
filesDir: "999_female_file_dir"
# filesDir: "03 - Tie Reports"
rawTieReportPath: "category_ties_unclean_run_11_1_2022.csv"
cleanTieReportPath: "cleaned_tie_report.csv"
cleanIndexReportPath: "cleaned_index_report.csv"
attributionDtPath: "attribution_table.csv"
pogDataPath: "raw_pog_data.csv"
configsDir: "configs"
configsTestDir: "test_configs"
pogsDir: "999_female_pogs"
# pogsDir: "05 - POGs" # TNT
# pogsDir: "99_item_add_pogs" # TNT one item add
templatePogsDir: "template_pogs_for_automation"
productLibraryDsnDir: "C:/Users/William.Roberts/OneDrive - Unilever/Documents/"
productLibraryDir: "C:/Users/William.Roberts/Desktop/performance_libraries"
outputDir: "outputs"
