functionDir: "~/r_code/functions"
categoryTag: "ic"
baseDir: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/06 - Ice Cream/2023/5.14.2023 IC Transition/"
filesDir: "03 - Tie Reports"
rawTieReportPath: "raw_ties_all_frozen_12_7_2022.csv"
cleanTieReportPath: "clean_ties_latest.csv"
cleanIndexReportPath: "clean_index_latest.csv"
attributionDtPath: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/00 - Automation & Reporting/PTIQ/Latest Master Attribution Workbook.xlsx"
attributionTableSheetName: "ICE CREAM"
pogDataPath: "raw_pog_data.csv"
configsDir: "configs"
configsTestDir: "test_configs"
pogsDir: "99 - POG_SANDBOX"
templatePogsDir: "template_pogs_for_automation"
productLibraryDsnDir: "C:/Users/William.Roberts/OneDrive - Unilever/Documents/"
productLibraryDir: "C:/Users/William.Roberts/Desktop/performance_libraries"
outputDir: "outputs"
ptiqFilesDir: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/00 - Automation & Reporting/PTIQ/2023/2023 Ice Cream PTIQ/Inputs"
