functionDir: "~/r_code/functions"
categoryTag: "pw"
baseDir: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/08 - Personal Wash/Oct 2023 Revision FEMALE"
filesDir: "03 - Tie Reports"
rawTieReportPath: "unclean_ties.csv"
cleanTieReportPath: "clean_ties_latest.csv"
cleanIndexReportPath: "clean_index_latest.csv"
attributionDtPath: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/00 - Automation & Reporting/PTIQ/Latest Master Attribution Workbook.xlsx"
attributionTableSheetName: "PW_FEMALE"
pogDataPath: "raw_pog_data.csv"
configsDir: "configs"
configsTestDir: "test_configs"
pogsDir: "05 - POGS"
templatePogsDir: "template_pogs_for_automation"
productLibraryDsnDir: "C:/Users/William.Roberts/OneDrive - Unilever/Documents/"
productLibraryDir: "C:/Users/William.Roberts/Desktop/performance_libraries"
outputDir: "outputs"
# dataDir: "C:/Users/William.Roberts/Unilever/Target POG HUB - Documents/00 - Automation & Reporting/Assortment Optimization/data/hbl/" # dev only
